# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QWidget(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, -10, 771, 521))
        self.bg.setStyleSheet("#bg{\n"
"background-color: #fc5404;\n"
"}")
        self.bg.setObjectName("bg")
        self.paymentButton = QtWidgets.QPushButton(self.bg)
        self.paymentButton.setGeometry(QtCore.QRect(440, 260, 71, 61))
        self.paymentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paymentButton.setStyleSheet("#paymentButton{\n"
"color: white;\n"
"background-color: #f9b208;\n"
"border: 1px solid white;\n"
"border-radius: 10px;\n"
"}")
        self.paymentButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/payments.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paymentButton.setIcon(icon)
        self.paymentButton.setIconSize(QtCore.QSize(45, 45))
        self.paymentButton.setObjectName("paymentButton")
        self.creditorsButton = QtWidgets.QPushButton(self.bg)
        self.creditorsButton.setGeometry(QtCore.QRect(240, 260, 71, 61))
        self.creditorsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.creditorsButton.setStyleSheet("#creditorsButton{\n"
"color: white;\n"
"background-color: #f9b208;\n"
"border: 1px solid white;\n"
"border-radius: 10px;\n"
"}")
        self.creditorsButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.creditorsButton.setIcon(icon1)
        self.creditorsButton.setIconSize(QtCore.QSize(50, 50))
        self.creditorsButton.setAutoDefault(False)
        self.creditorsButton.setDefault(False)
        self.creditorsButton.setObjectName("creditorsButton")
        self.collectibleButton = QtWidgets.QPushButton(self.bg)
        self.collectibleButton.setGeometry(QtCore.QRect(340, 260, 71, 61))
        self.collectibleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.collectibleButton.setStyleSheet("#collectibleButton{\n"
"color: white;\n"
"background-color: #f9b208;\n"
"border: 1px solid white;\n"
"border-radius: 10px;\n"
"}")
        self.collectibleButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/collectible.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.collectibleButton.setIcon(icon2)
        self.collectibleButton.setIconSize(QtCore.QSize(45, 45))
        self.collectibleButton.setObjectName("collectibleButton")
        self.label = QtWidgets.QLabel(self.bg)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 70, 761, 81))
        self.label.setStyleSheet("#label {\n"
"color: white;\n"
"font: 25 46pt \"Bodoni MT Poster Compressed\";\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.bg)
        self.widget.setGeometry(QtCore.QRect(160, 200, 451, 41))
        self.widget.setStyleSheet("#widget{\n"
"background-color: white;\n"
"border: 1px white;\n"
"border-radius: 20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 5, 341, 30))
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"border: 1px white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.clearButton = QtWidgets.QPushButton(self.widget)
        self.clearButton.setGeometry(QtCore.QRect(370, 10, 21, 23))
        self.clearButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearButton.setStyleSheet("#clearButton{\n"
"color: blue;\n"
"font: 10pt \"Segoe UI\";\n"
"border: TRANSPARENT;\n"
"}")
        self.clearButton.setFlat(True)
        self.clearButton.setObjectName("clearButton")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(383, 10, 20, 21))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.searchButton = QtWidgets.QPushButton(self.widget)
        self.searchButton.setGeometry(QtCore.QRect(400, 10, 41, 23))
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon3)
        self.searchButton.setFlat(True)
        self.searchButton.setObjectName("searchButton")
        self.borrowerLabel = QtWidgets.QLabel(self.bg)
        self.borrowerLabel.setGeometry(QtCore.QRect(240, 340, 71, 13))
        self.borrowerLabel.setStyleSheet("#borrowerLabel{\n"
"color: white;\n"
"font: 12px;\n"
"}")
        self.borrowerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.borrowerLabel.setObjectName("borrowerLabel")
        self.collectibleLabel = QtWidgets.QLabel(self.bg)
        self.collectibleLabel.setGeometry(QtCore.QRect(340, 340, 71, 13))
        self.collectibleLabel.setStyleSheet("#collectibleLabel{\n"
"color: white;\n"
"font: 12px;\n"
"}")
        self.collectibleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.collectibleLabel.setObjectName("collectibleLabel")
        self.paymentLabel = QtWidgets.QLabel(self.bg)
        self.paymentLabel.setGeometry(QtCore.QRect(440, 340, 71, 13))
        self.paymentLabel.setStyleSheet("#paymentLabel{\n"
"color: white;\n"
"font: 12px;\n"
"}")
        self.paymentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.paymentLabel.setObjectName("paymentLabel")
        self.duetodayLabel = QtWidgets.QLabel(self.bg)
        self.duetodayLabel.setGeometry(QtCore.QRect(240, 460, 71, 13))
        self.duetodayLabel.setStyleSheet("#duetodayLabel{\n"
"color: white;\n"
"font: 12px;\n"
"}")
        self.duetodayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.duetodayLabel.setObjectName("duetodayLabel")
        self.duetodayButton = QtWidgets.QPushButton(self.bg)
        self.duetodayButton.setGeometry(QtCore.QRect(240, 380, 71, 61))
        self.duetodayButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.duetodayButton.setStyleSheet("#duetodayButton{\n"
"color: white;\n"
"background-color: #f9b208;\n"
"border: 1px solid white;\n"
"border-radius: 10px;\n"
"}")
        self.duetodayButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/due today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.duetodayButton.setIcon(icon4)
        self.duetodayButton.setIconSize(QtCore.QSize(30, 30))
        self.duetodayButton.setObjectName("duetodayButton")
        self.addNewBorrower = QtWidgets.QPushButton(self.bg)
        self.addNewBorrower.setGeometry(QtCore.QRect(600, 60, 51, 51))
        self.addNewBorrower.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addNewBorrower.setStyleSheet("#addNewUser{\n"
"background-color: white;\n"
"border: 1px solid white;\n"
"border-radius: 25;\n"
"}")
        self.addNewBorrower.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../img/add new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNewBorrower.setIcon(icon5)
        self.addNewBorrower.setIconSize(QtCore.QSize(50, 50))
        self.addNewBorrower.setFlat(False)
        self.addNewBorrower.setObjectName("addNewUser")
        self.listWidget = QtWidgets.QListWidget(self.bg)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(160, 250, 451, 25))
        self.listWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget.setObjectName("listWidget")
        self.paymentButton.raise_()
        self.creditorsButton.raise_()
        self.collectibleButton.raise_()
        self.label.raise_()
        self.borrowerLabel.raise_()
        self.collectibleLabel.raise_()
        self.paymentLabel.raise_()
        self.duetodayLabel.raise_()
        self.duetodayButton.raise_()
        self.widget.raise_()
        self.addNewBorrower.raise_()
        self.listWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.clearButton.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lending Company"))
        self.label.setStatusTip(_translate("MainWindow", "lending corporation"))
        self.label.setText(_translate("MainWindow", "Lending Co."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search borrower"))
        self.clearButton.setText(_translate("MainWindow", "X"))
        self.borrowerLabel.setText(_translate("MainWindow", "Borrowers"))
        self.collectibleLabel.setText(_translate("MainWindow", "Collectibles"))
        self.paymentLabel.setText(_translate("MainWindow", "Payments"))
        self.duetodayLabel.setText(_translate("MainWindow", "Due Today"))
